import { resolve } from 'node:path'

/**
 * Root of the `@rublox/server` package. Both `src/` (run by tsx or vitest) and `dist/` (the
 * esbuild bundle) sit one level below it, so the same relative path works in development, in the
 * bundle, and in the Docker image, which keeps the `apps/server` layout.
 */
export const serverRoot = resolve(import.meta.dirname, '..')

/** Drizzle migrations generated by drizzle-kit. */
export const migrationsFolder = resolve(serverRoot, 'drizzle')

/** Default locations of the built front-ends (`apps/studio/dist`, `apps/player/dist`). */
export const defaultStudioDist = resolve(serverRoot, '../studio/dist')
export const defaultPlayerDist = resolve(serverRoot, '../player/dist')
