import type { IconName } from '@rublox/catalog'
import {
  Activity,
  AlarmClock,
  Apple,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AudioLines,
  Battery,
  Bell,
  Bike,
  Bird,
  Bookmark,
  BookOpen,
  Bot,
  Brush,
  Bug,
  Bus,
  CakeSlice,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  Check,
  ChevronRight,
  Clipboard,
  Clock,
  Cloud,
  CloudRain,
  Coffee,
  Compass,
  Contact,
  Crown,
  Dice5,
  Dog,
  Download,
  Droplet,
  Dumbbell,
  Eye,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Frown,
  Gamepad2,
  Ghost,
  Gift,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Hourglass,
  House,
  IceCreamCone,
  Image,
  Info,
  Key,
  Laugh,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link,
  List,
  Lock,
  LockOpen,
  type LucideIcon,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Moon,
  Music,
  Navigation,
  Palette,
  PartyPopper,
  Pause,
  Pencil,
  Phone,
  Pizza,
  Plane,
  Play,
  Plus,
  Puzzle,
  QrCode,
  Rabbit,
  RefreshCw,
  Rocket,
  ScanLine,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  Shirt,
  ShoppingCart,
  SkipBack,
  SkipForward,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Speech,
  Square,
  Star,
  Sun,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TrainFront,
  Trash2,
  TreePine,
  Trophy,
  Tv,
  Umbrella,
  Upload,
  User,
  Users,
  Utensils,
  Vibrate,
  Video,
  Volume2,
  Wifi,
  X,
  Zap,
} from 'lucide-react'

/** The drawing of each name of `ICON_NAMES` (Lucide, ISC licence). */
export const ICONS: Record<IconName, LucideIcon> = {
  house: House,
  star: Star,
  heart: Heart,
  settings: Settings,
  user: User,
  users: Users,
  search: Search,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  info: Info,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  camera: Camera,
  image: Image,
  music: Music,
  play: Play,
  pause: Pause,
  square: Square,
  'skip-forward': SkipForward,
  'skip-back': SkipBack,
  'volume-2': Volume2,
  mic: Mic,
  'map-pin': MapPin,
  map: MapIcon,
  navigation: Navigation,
  phone: Phone,
  mail: Mail,
  'message-circle': MessageCircle,
  send: Send,
  'share-2': Share2,
  download: Download,
  upload: Upload,
  'trash-2': Trash2,
  pencil: Pencil,
  bookmark: Bookmark,
  flag: Flag,
  gift: Gift,
  'shopping-cart': ShoppingCart,
  list: List,
  'layout-grid': LayoutGrid,
  menu: Menu,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'chevron-right': ChevronRight,
  'refresh-cw': RefreshCw,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  snowflake: Snowflake,
  thermometer: Thermometer,
  umbrella: Umbrella,
  zap: Zap,
  flame: Flame,
  droplet: Droplet,
  leaf: Leaf,
  'tree-pine': TreePine,
  'flower-2': Flower2,
  dog: Dog,
  cat: Cat,
  bird: Bird,
  fish: Fish,
  rabbit: Rabbit,
  bug: Bug,
  rocket: Rocket,
  plane: Plane,
  car: Car,
  bike: Bike,
  bus: Bus,
  'train-front': TrainFront,
  'gamepad-2': Gamepad2,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  'dice-5': Dice5,
  puzzle: Puzzle,
  palette: Palette,
  brush: Brush,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  lightbulb: Lightbulb,
  smile: Smile,
  frown: Frown,
  laugh: Laugh,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  lock: Lock,
  'lock-open': LockOpen,
  key: Key,
  eye: Eye,
  wifi: Wifi,
  battery: Battery,
  globe: Globe,
  link: Link,
  'qr-code': QrCode,
  'scan-line': ScanLine,
  timer: Timer,
  'alarm-clock': AlarmClock,
  hourglass: Hourglass,
  pizza: Pizza,
  apple: Apple,
  coffee: Coffee,
  'cake-slice': CakeSlice,
  'ice-cream-cone': IceCreamCone,
  utensils: Utensils,
  shirt: Shirt,
  footprints: Footprints,
  dumbbell: Dumbbell,
  headphones: Headphones,
  video: Video,
  film: Film,
  tv: Tv,
  calculator: Calculator,
  clipboard: Clipboard,
  contact: Contact,
  sparkles: Sparkles,
  'party-popper': PartyPopper,
  ghost: Ghost,
  bot: Bot,
  smartphone: Smartphone,
  vibrate: Vibrate,
  speech: Speech,
  'audio-lines': AudioLines,
  activity: Activity,
  compass: Compass,
  shield: Shield,
}

export function AppIcon({
  name,
  size = 24,
  color,
  strokeWidth,
  label,
}: {
  name: string
  size?: number
  color?: string
  strokeWidth?: number
  /** Read by screen readers; without it the icon is decorative. */
  label?: string
}) {
  const Icon = ICONS[name as IconName] ?? Star
  return (
    <Icon
      size={size}
      color={color ?? 'currentColor'}
      strokeWidth={strokeWidth}
      aria-hidden={label ? undefined : true}
      aria-label={label || undefined}
      role={label ? 'img' : undefined}
    />
  )
}
