import { defineComponent } from '../component.ts'
import { event, method, prop } from '../define.ts'

/** Common properties a scene child keeps: the others are about flex layout. */
export const SCENE_CHILD_OMIT = [
  'width',
  'height',
  'grow',
  'alignSelf',
  'margin',
  'padding',
  'background',
  'borderWidth',
  'borderColor',
  'radius',
  'shadow',
] as const

const sprite = { kind: 'component', componentType: 'Sprite' } as const

/**
 * A sprite (SPEC § 4.4, Jeu): an image or an emoji that moves in a game scene, with speed,
 * gravity, bounces, collisions, touch and drag. Its clones share its blocks.
 */
export const Sprite = defineComponent({
  type: 'Sprite',
  category: 'game',
  icon: 'ghost',
  visible: true,
  container: false,
  junior: true,
  parents: ['GameScene'],
  clonable: true,
  omitCommon: SCENE_CHILD_OMIT,
  props: {
    costumes: prop.images({ default: ['🐱'], group: 'content', junior: true }),
    costume: prop.number({ default: 1, min: 1, step: 1, group: 'content', blocks: 'get-set' }),
    x: prop.number({ default: 180, group: 'layout', junior: true, blocks: 'get-set' }),
    y: prop.number({ default: 320, group: 'layout', junior: true, blocks: 'get-set' }),
    width: prop.number({
      default: 64,
      min: 1,
      max: 4000,
      group: 'layout',
      junior: true,
      blocks: 'get-set',
    }),
    height: prop.number({
      default: 64,
      min: 1,
      max: 4000,
      group: 'layout',
      junior: true,
      blocks: 'get-set',
    }),
    rotation: prop.number({ default: 0, group: 'layout', junior: true, blocks: 'get-set' }),
    draggable: prop.boolean({ default: false, group: 'content', junior: true, blocks: 'get-set' }),
    vx: prop.number({ default: 0, group: 'advanced', junior: true, blocks: 'get-set' }),
    vy: prop.number({ default: 0, group: 'advanced', junior: true, blocks: 'get-set' }),
    gravity: prop.number({ default: 0, group: 'advanced', junior: true, blocks: 'get-set' }),
    bounce: prop.number({
      default: 100,
      min: 0,
      max: 100,
      step: 5,
      group: 'advanced',
      blocks: 'get-set',
    }),
    edges: prop.enum(['scene', 'stop', 'bounce', 'pass'], {
      default: 'scene',
      group: 'advanced',
      blocks: 'get-set',
    }),
    collision: prop.enum(['box', 'circle', 'none'], {
      default: 'box',
      group: 'advanced',
      blocks: 'get-set',
    }),
    solid: prop.boolean({ default: false, group: 'advanced', blocks: 'get-set' }),
    clone: prop.boolean({ default: false, group: 'advanced', blocks: 'get', live: true }),
  },
  events: {
    tap: event({ junior: true }),
    hit: event({ junior: true, filter: sprite, args: { other: sprite } }),
    edge: event({
      junior: true,
      filter: { kind: 'enum', values: ['top', 'bottom', 'left', 'right'] },
      args: { edge: { kind: 'string' } },
    }),
    clone: event({ junior: true }),
    drag: event({ args: { x: { kind: 'number' }, y: { kind: 'number' } } }),
    drop: event(),
  },
  methods: {
    moveForward: method({ junior: true, args: { steps: { kind: 'number', default: 10 } } }),
    moveBy: method({
      junior: true,
      args: { dx: { kind: 'number', default: 10 }, dy: { kind: 'number', default: 0 } },
    }),
    goTo: method({
      junior: true,
      args: { x: { kind: 'number', default: 180 }, y: { kind: 'number', default: 320 } },
    }),
    glideTo: method({
      junior: true,
      async: true,
      args: {
        x: { kind: 'number', default: 180 },
        y: { kind: 'number', default: 320 },
        seconds: { kind: 'number', default: 1 },
      },
    }),
    turn: method({ junior: true, args: { degrees: { kind: 'number', default: 15 } } }),
    pointTowards: method({ junior: true, args: { target: sprite } }),
    pointAt: method({
      args: { x: { kind: 'number', default: 180 }, y: { kind: 'number', default: 0 } },
    }),
    nextCostume: method({ junior: true }),
    clone: method({ junior: true }),
    delete: method({ junior: true }),
    isTouching: method({ junior: true, args: { target: sprite }, returns: 'boolean' }),
    distanceTo: method({ args: { target: sprite }, returns: 'number' }),
  },
  strings: {
    fr: {
      label: 'Lutin',
      prefix: 'Lutin',
      description: 'Un personnage ou un objet qui bouge dans la scène.',
      help: 'Un lutin est une image ou un émoji posé dans une scène de jeu. Il peut avancer, tourner, glisser, tomber avec la gravité, rebondir, et savoir quand il touche un autre lutin ou un bord. Ses costumes sont ses différentes images. Crée des clones pour faire apparaître plein de copies : dans les blocs « quand … », le nom du lutin désigne alors le clone concerné. Un clone qui sort complètement de la scène disparaît tout seul.',
      example: 'Quand Pomme touche Panier, ajouter 1 au score puis supprimer Pomme',
      props: {
        costumes: 'costumes',
        costume: 'numéro du costume',
        x: 'x',
        y: 'y',
        width: 'largeur',
        height: 'hauteur',
        rotation: 'rotation',
        draggable: 'se glisse au doigt',
        vx: 'vitesse x',
        vy: 'vitesse y',
        gravity: 'gravité',
        bounce: 'rebond (%)',
        edges: 'bords',
        collision: 'forme des collisions',
        solid: 'solide',
        clone: 'est un clone',
      },
      events: {
        tap: 'quand on touche %1',
        hit: 'quand %1 touche %2',
        edge: 'quand %1 touche %2',
        clone: 'quand %1 apparaît comme clone',
        drag: 'quand on glisse %1',
        drop: 'quand on lâche %1',
      },
      methods: {
        moveForward: 'avancer %1 de %2 pas',
        moveBy: 'déplacer %1 de x %2 y %3',
        goTo: 'mettre %1 à x %2 y %3',
        glideTo: 'faire glisser %1 vers x %2 y %3 en %4 s',
        turn: 'tourner %1 de %2 degrés',
        pointTowards: 'orienter %1 vers %2',
        pointAt: 'orienter %1 vers x %2 y %3',
        nextCostume: 'costume suivant pour %1',
        clone: 'créer un clone de %1',
        delete: 'supprimer %1',
        isTouching: '%1 touche %2',
        distanceTo: 'distance de %1 à %2',
      },
      enums: {
        edges: {
          scene: 'Comme la scène',
          stop: 'Arrêtent',
          bounce: 'Font rebondir',
          pass: 'Laissent sortir',
        },
        collision: { box: 'Boîte', circle: 'Cercle', none: 'Aucune' },
      },
      eventArgs: {
        hit: { other: 'l’autre lutin' },
        edge: { edge: 'bord touché' },
        drag: { x: 'x du doigt', y: 'y du doigt' },
      },
      filters: {
        hit: { any: 'un autre lutin' },
        edge: {
          any: 'un bord',
          top: 'le bord du haut',
          bottom: 'le bord du bas',
          left: 'le bord gauche',
          right: 'le bord droit',
        },
      },
    },
    en: {
      label: 'Sprite',
      prefix: 'Sprite',
      description: 'A character or an object that moves in the scene.',
      help: 'A sprite is an image or an emoji in a game scene. It can move, turn, glide, fall with gravity, bounce, and tell when it touches another sprite or an edge. Its costumes are its different pictures. Create clones to make many copies appear: in "when …" blocks, the sprite’s name then means the clone concerned. A clone that leaves the scene completely disappears on its own.',
      example: 'When Apple touches Basket, add 1 to the score then delete Apple',
      props: {
        costumes: 'costumes',
        costume: 'costume number',
        x: 'x',
        y: 'y',
        width: 'width',
        height: 'height',
        rotation: 'rotation',
        draggable: 'can be dragged',
        vx: 'x speed',
        vy: 'y speed',
        gravity: 'gravity',
        bounce: 'bounciness (%)',
        edges: 'edges',
        collision: 'collision shape',
        solid: 'solid',
        clone: 'is a clone',
      },
      events: {
        tap: 'when %1 is tapped',
        hit: 'when %1 touches %2',
        edge: 'when %1 touches %2',
        clone: 'when %1 starts as a clone',
        drag: 'when %1 is dragged',
        drop: 'when %1 is dropped',
      },
      methods: {
        moveForward: 'move %1 %2 steps',
        moveBy: 'move %1 by x %2 y %3',
        goTo: 'put %1 at x %2 y %3',
        glideTo: 'glide %1 to x %2 y %3 in %4 s',
        turn: 'turn %1 by %2 degrees',
        pointTowards: 'point %1 towards %2',
        pointAt: 'point %1 towards x %2 y %3',
        nextCostume: 'next costume for %1',
        clone: 'create a clone of %1',
        delete: 'delete %1',
        isTouching: '%1 touches %2',
        distanceTo: 'distance from %1 to %2',
      },
      enums: {
        edges: {
          scene: 'Like the scene',
          stop: 'Stop',
          bounce: 'Bounce',
          pass: 'Let through',
        },
        collision: { box: 'Box', circle: 'Circle', none: 'None' },
      },
      eventArgs: {
        hit: { other: 'the other sprite' },
        edge: { edge: 'edge touched' },
        drag: { x: 'finger x', y: 'finger y' },
      },
      filters: {
        hit: { any: 'another sprite' },
        edge: {
          any: 'an edge',
          top: 'the top edge',
          bottom: 'the bottom edge',
          left: 'the left edge',
          right: 'the right edge',
        },
      },
    },
  },
})
